general {
    hide_cursor = true
    ignore_empty_input = true
    fail_timeout = 2000
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 2.0, linear
}

# 真っ黒な背景
background {
    monitor =
    color = rgba(000000ff)
}

# 時刻
label {
    monitor =
    text = $TIME
    color = rgba(f66e25ff)
    font_size = 96
    font_family = Noto Sans CJK JP

    position = 0, 150
    halign = center
    valign = center
}

# ユーザー名
# label {
#     monitor =
#     text = [ $USER ]
#     color = rgba(f66e25ff)
#     font_size = 22
#     font_family = Noto Sans CJK JP

#     position = 0, 80
#     halign = center
#     valign = center
# }

# パスワード入力欄
input-field {
    monitor =
    size = 360, 54
    position = 0, 0
    halign = center
    valign = center

    outline_thickness = 2
    rounding = 0

    inner_color = rgba(000000ff)
    outer_color = rgba(f66e25ff)
    font_color = rgba(f66e25ff)

    check_color = rgba(f66e25ff)
    fail_color = rgba(f66e25ff)

    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true

    fade_on_empty = false

    placeholder_text = <b>LOCKED</b>
    fail_text = <b>REFUSED ($ATTEMPTS)</b>

    font_family = Noto Sans CJK JP
}
